version: "3"
services:
  web:
    image: my-node-app
    container_name: web
    ports:
      - 3000:3000
    networks:
      - my_network
  db:
    image: mongo:latest
    container_name: db
    ports:
      - 27017:27017
    networks:
      - my_network
networks:
  my_network:
    name: my_network
    driver: bridge
